const elfbarD1Flavours = [
  "Apple Orange Bubblegum",
  "Kiwi Guava Grape",
  "Mango Lychee Bubblegum",
  "Mango Strawberry Ice Cream",
  "Peach Lychee Blackcurrant",
  "Ribena Lychee",
  "Strawberry Guava",
  "Lychee Juicy Peach",
  "Cola",
  "Mixed Berry",
  "Blueberry",
  "Watermelon",
  "Tropical Grape",
  "Pink Peach",
];

const spacebarFlavours = [
  "POCARI SWEET",
  "DOUBLE MANGO",
  "GUMMY BEAR",
  "SWEET PINEAPPLE",
  "PUMKIN CREAM CAKE",
  "PEACH MANGO",
  "VANILLA LATTE FRAPPUCCINO",
  "BERRY PEACH",
  "PEPPERMINT",
  "BLUE RASPBERRY",
  "LEMON COLA",
  "STRAWBERRY VANILLA",
  "KIWI PASSION FRUIT",
  "CARAMEL BUTTER POPCORN",
  "PINK SPRITE",
  "CALPIS",
];

export const products = [
  {
    id: 1,
    name: "ELFBAR RAYA D1",
    category: "Disposable Vape",
    price: "RM42",
    rating: "4.8",
    tag: "Best seller",
    puffs: "",
    stock: 12,
    nicotine: "3%",
    description: "Compact disposable vape with smooth flavour delivery.",
    flavours: elfbarD1Flavours,
    image:
      "https://d2j6dbq0eux0bg.cloudfront.net/images/44274057/4151158064.png",
  },
  {
    id: 2,
    name: "ELFBAR S1",
    category: "Disposable Vape",
    price: "RM45",
    rating: "4.7",
    tag: "New",
    puffs: "",
    stock: 9,
    nicotine: "3%",
    description: "Easy carry disposable device with popular icy fruit options.",
    flavours: [
      "Mango Mix",
      "Honeydew Mix",
      "Grape Ice",
      "Lychee Juicy Peach",
      "Mango Lychee Bubblegum",
      "Mango Strawberry Ice Cream",
      "Peach Lychee Blackcurrant",
      "Kiwi Mango Watermelon",
      "Strawberry Guava",
      "Kiwi Guava Grape",
      "Strawberry Mango",
      "Mango Blackcurrant",
      "Strawberry Ice",
      "Peach Strawberry",
    ],
    image:
      "https://p16-oec-sg.ibyteimg.com/tos-alisg-i-aphluv4xwc-sg/aa5d6780ffc14fbcaff06ce6f967a736~tplv-aphluv4xwc-resize-jpeg:700:0.jpeg",
  },
  {
    id: 3,
    name: "EFLBAR ICEKING",
    category: "E-Liquid",
    price: "RM48",
    rating: "4.6",
    tag: "Limited",
    puffs: "30,000 Puffs",
    stock: 6,
    nicotine: "3mg",
    description: "Icy profile made for customers who prefer a cooler finish.",
    flavours: ["Lychee Ice", "Honeydew Mint", "Lemon Soda"],
    image:
      "https://cdn.shopify.com/s/files/1/0573/8463/2454/files/elfbar-ice-king-30000-puffs-disposable-vape-grape-vapes-uae-smoke-souq-546.webp",
  },
  {
    id: 4,
    name: "SPACEBAR by DOTMOD",
    category: "Disposable Vape",
    price: "RM48",
    rating: "4.9",
    tag: "Popular",
    puffs: "",
    stock: 8,
    nicotine: "Device only",
    description: "Starter kit with simple controls and convenient USB-C charging.",
    flavours: spacebarFlavours,
    image:
      "https://vapehaus.com.my/cdn/shop/files/space_bar_poster_3.jpg?v=1778158986&width=1445",
  },
  {
    id: 5,
    name: "GYPEO 30,000 Puffs",
    category: "Disposable Vape",
    price: "RM55",
    rating: "4.5",
    tag: "Trending",
    puffs: "30,000 Puffs",
    stock: 10,
    nicotine: "2%",
    description: "Bright tropical disposable with sweet fruit flavours.",
    flavours: ["Pineapple Ice", "Passion Fruit", "Guava Mint"],
    image:
      "https://static.24hvape.com/wp-content/uploads/2024/09/07150030/24h-vape-galaxy-30000-gypsophila-30000-puffs-gazzbar-30000--654x690.jpg.webp",
  },
];
