const elfbarD1Flavours = [
  "Apple Orange Bubblegum",
  "Kiwi Guava Grape",
  "Mango Lychee Bubblegum",
  "Mango Strawberry Ice Cream",
  "Peach Lychee Blackcurrant",
  "Ribena Lychee",
  "Strawberry Guava",
  "Lychee Juicy Peach",
  "Cola",
  "Mixed Berry",
  "Blueberry",
  "Watermelon",
  "Tropical Grape",
  "Pink Peach",
];

export const products = [
  {
    id: 1,
    name: "ELFBAR RAYA D1",
    category: "Disposable Vape",
    price: "RM42",
    rating: "4.8",
    tag: "Best seller",
    nicotine: "3%",
    description: "Compact disposable vape with smooth flavour delivery.",
    flavours: elfbarD1Flavours,
    image:
      "https://ecloudsbd.com/assets/product-images/54c13bbd79798165a965809ac821266b.elf-bar-raya-d1-13000puffs--ribena-lychee.webp",
  },
  {
    id: 2,
    name: "ELFBAR S1",
    category: "Disposable Vape",
    price: "RM45",
    rating: "4.7",
    tag: "New",
    nicotine: "3%",
    description: "Easy carry disposable device with popular icy fruit options.",
    flavours: [
      "Mango Mix",
      "Honeydew Mix",
      "Grape Ice",
      "Lychee Juicy Peach",
      "Mango Lychee Bubblegum",
      "Mango Strawberry Ice Cream",
      "Peach Lychee Blackcurrant",
      "Kiwi Mango Watermelon",
      "Strawberry Guava",
      "Kiwi Guava Grape",
      "Strawberry Mango",
      "Mango Blackcurrant",
      "Strawberry Ice",
      "Peach Strawberry",
    ],
    image:
      "https://p16-oec-sg.ibyteimg.com/tos-alisg-i-aphluv4xwc-sg/aa5d6780ffc14fbcaff06ce6f967a736~tplv-aphluv4xwc-resize-jpeg:700:0.jpeg",
  },
  {
    id: 3,
    name: "EFLBAR ICEKING",
    category: "E-Liquid",
    price: "RM48",
    rating: "4.6",
    tag: "Limited",
    nicotine: "3mg",
    description: "Icy profile made for customers who prefer a cooler finish.",
    flavours: ["Lychee Ice", "Honeydew Mint", "Lemon Soda"],
    image:
      "https://cdn.shopify.com/s/files/1/0573/8463/2454/files/elfbar-ice-king-30000-puffs-disposable-vape-grape-vapes-uae-smoke-souq-546.webp",
  },
  {
    id: 4,
    name: "SPACEBAR by DOTMOD",
    category: "Disposable Vape",
    price: "RM48",
    rating: "4.9",
    tag: "Popular",
    nicotine: "Device only",
    description: "Starter kit with simple controls and convenient USB-C charging.",
    flavours: ["Mango Peach", "Grape Ice", "Blue Razz"],
    image:
      "https://hypervape.my/wp-content/uploads/2024/08/456580586_528462423191481_1793938225607092952_n.jpg",
  },
  {
    id: 5,
    name: "GYPEO 30,000 Puffs",
    category: "Disposable Vape",
    price: "RM55",
    rating: "4.5",
    tag: "Trending",
    nicotine: "2%",
    description: "Bright tropical disposable with sweet fruit flavours.",
    flavours: ["Pineapple Ice", "Passion Fruit", "Guava Mint"],
    image:
      "https://static.24hvape.com/wp-content/uploads/2024/09/07150030/24h-vape-galaxy-30000-gypsophila-30000-puffs-gazzbar-30000--654x690.jpg.webp",
  },
  {
    id: 6,
    name: "Classic Tobacco Salt",
    category: "E-Liquid",
    price: "RM32",
    rating: "4.6",
    tag: "Smooth",
    nicotine: "30mg",
    description: "Classic tobacco-style salt nic with smooth blends.",
    flavours: ["Virginia Tobacco", "Vanilla Tobacco", "Caramel Blend"],
    image:
      "https://images.unsplash.com/photo-1505577058444-a3dab90d4253?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 7,
    name: "Arctic Mint 7000",
    category: "Disposable Vape",
    price: "RM48",
    rating: "4.7",
    tag: "Ice hit",
    nicotine: "3%",
    description: "Strong mint disposable for customers who like a cold draw.",
    flavours: ["Peppermint Ice", "Spearmint", "Menthol Blast"],
    image:
      "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 8,
    name: "Berry Rush Salt",
    category: "E-Liquid",
    price: "RM36",
    rating: "4.8",
    tag: "Fruity",
    nicotine: "35mg",
    description: "Berry salt nic range with sweet and icy profiles.",
    flavours: ["Mixed Berries", "Raspberry Ice", "Blackcurrant"],
    image:
      "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 9,
    name: "Mist Pod Cartridge",
    category: "Replacement Pods",
    price: "RM25",
    rating: "4.5",
    tag: "Restock",
    nicotine: "Empty pod",
    description: "Replacement cartridges for daily pod-system use.",
    flavours: ["0.8 Ohm Mesh", "1.0 Ohm Smooth", "Leak Resistant"],
    image:
      "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 10,
    name: "Dessert Cloud Salt",
    category: "E-Liquid",
    price: "RM38",
    rating: "4.6",
    tag: "Sweet",
    nicotine: "30mg",
    description: "Dessert-inspired flavours with creamy sweet notes.",
    flavours: ["Vanilla Custard", "Caramel Latte", "Creamy Banana"],
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 11,
    name: "Volt Mini Device",
    category: "Pod System",
    price: "RM99",
    rating: "4.7",
    tag: "Compact",
    nicotine: "Device only",
    description: "Small pod system for simple pocket-friendly use.",
    flavours: ["Pocket Size", "Fast Charge", "Auto Draw"],
    image:
      "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 12,
    name: "Citrus Spark 5000",
    category: "Disposable Vape",
    price: "RM43",
    rating: "4.4",
    tag: "Zesty",
    nicotine: "2%",
    description: "Citrus disposable with a bright and refreshing finish.",
    flavours: ["Orange Soda", "Lime Ice", "Grapefruit Mint"],
    image:
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=900&q=80",
  },
];
